[mgr]
show_hidden = true

[preview]
max_width  = 1920
max_height = 1920

[opener]
edit = [
  { run = 'micro "$@"', block = true, for = "unix" },
]
code = [
   { run = 'code "$@"', block = true, for = "unix" },
]
ppt = [
  { run = 'open -a "Microsoft PowerPoint" "$@"', block = true, for = "unix" },
]
open = [
  { run = 'open "$@"', block = true, for = "unix" },
]


[open]
prepend_rules = [
  { name = "*.csv", use = "code" },
  { name = "*.pptx", use = "ppt" },
  { name = "*.html", use = "open" },
]

[plugin]
prepend_previewers = [
  { mime = "image/tiff", run = "magick" },
]
append_previewers = [
  { name = "*.jsonl", run = "json" },
]
