[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"

[[mgr.prepend_keymap]]
on = "<C-y>"
run = "plugin system-clipboard"

[[mgr.prepend_keymap]]
on = "<C-p>"
run = "shell 'cb paste' --block"
desc = "Paste from clipboard"

[[mgr.prepend_keymap]]
on = ["s", "s"]
run = 'search --via=fd --args="--no-hidden"'
desc = "Search"

[[mgr.prepend_keymap]]
on = ["s", "d"]
run = 'search --via=fd --args="-t d --no-hidden"'
desc = "Search directories"

[[mgr.prepend_keymap]]
on = ["s", "f"]
run = 'search --via=fd --args="-t f --no-hidden"'
desc = "Search files"

[[mgr.prepend_keymap]]
on = ["s", "z"]
run = "plugin fd-fzf"
desc = "Jump to directory"

[[mgr.prepend_keymap]]
on = ["g", "g"]
run = "shell 'lazygit' --block"
desc = "Lazygit"

[[mgr.prepend_keymap]]
on = ["g", "r"]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "Git Root"

[[mgr.prepend_keymap]]
on = ["g", "v"]
run = "plugin ghq"
desc = "Go ghq repo"

[[mgr.prepend_keymap]]
on = ["c", "r"]
run = "shell --confirm 'git_root=$(git rev-parse --show-toplevel 2>/dev/null) && [ -n \"$git_root\" ] && printf \"%s\" \"$0\" | sed \"s|^$git_root/||\" | cb copy'"
desc = "Copy git-relative path"
