[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin smart-enter"

[[mgr.prepend_keymap]]
on = "<C-y>"
run = "plugin system-clipboard"

[[mgr.prepend_keymap]]
on = "<C-p>"
run = "shell 'cb paste' --block"
desc = "Paste from clipboard"

[[mgr.prepend_keymap]]
on = "b"
run = "plugin bunny"

[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"

[[mgr.prepend_keymap]]
on = ["s", "s"]
run = "search --via=fd"
desc = "Search"

[[mgr.prepend_keymap]]
on = ["s", "d"]
run = "search --via=fd --args='-t d'"
desc = "Search directories"

[[mgr.prepend_keymap]]
on = ["s", "f"]
run = "search --via=fd --args='-t f'"
desc = "Search files"
