[mgr]
show_hidden = true
ratio = [0, 1, 3]

[preview]
max_width = 1920
max_height = 1920

[opener]
edit = [{ run = 'nvim "$@"', block = true, for = "unix" }]
default = [{ run = 'open "$@"', block = false, for = "unix" }]

[open]
prepend_rules = [
  { name = "*.csv", use = "default" },
  { name = "*.pptx", use = "default" },
  { name = "*.html", use = "default" },
  { name = "*.MP4", use = "default" },
  { name = "*.mp4", use = "default" },
]

[plugin]
prepend_previewers = [{ mime = "image/tiff", run = "magick" }]
append_previewers = [{ name = "*.jsonl", run = "json" }]

[[plugin.prepend_fetchers]]
id = "git"
url = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
url = "*/"
run = "git"
