[mgr]
show_hidden = true

[preview]
max_width  = 1920
max_height = 1920

[opener]
edit = [
  { run = 'micro "$@"', block = true, for = "unix" },
]
default = [
  { run = 'open "$@"', block = false, for = "unix" },
]

[open]
prepend_rules = [
  { name = "*.csv", use = "default" },
  { name = "*.pptx", use = "default" },
  { name = "*.html", use = "default" },
  { name = "*.MP4", use = "default" },
  { name = "*.mp4", use = "default" },
]

[plugin]
prepend_previewers = [
  { mime = "image/tiff", run = "magick" },
]
append_previewers = [
  { name = "*.jsonl", run = "json" },
]
